batches = """
    CREATE TABLE stg_reference.batches
    (
        batch_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        crt_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("batch_id")
    );
    """

table_list = {
    'batches': batches
}