sports = """
    CREATE TABLE raw_the_odds_api.sports
    (
        pk bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        json jsonb NOT NULL,
        batch_id bigint NOT NULL,
        crt_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("pk")
    );
    """

odds = """
    CREATE TABLE raw_the_odds_api.odds
    (
        pk bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        json jsonb NOT NULL,
        batch_id bigint NOT NULL,
        crt_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("pk")
    );
    """

scores = """
    CREATE TABLE raw_the_odds_api.scores
    (
        pk bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        json jsonb NOT NULL,
        batch_id bigint NOT NULL,
        crt_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("pk")
    );
    """

events = """
    CREATE TABLE raw_the_odds_api.events
    (
        pk bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        json jsonb NOT NULL,
        batch_id bigint NOT NULL,
        crt_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("pk")
    );
    """

table_list = {
    'sports': sports,
    'odds': odds,
    'scores': scores,
    'events': events
}