sports = """
    CREATE TABLE raw_the_odds_api.sports
    (
        sports_sid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        json jsonb NOT NULL,
        batch_id bigint NOT NULL,
        crt_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("sports_sid")
    );
    """

table_list = {
    'sports': sports
}